#!/bin/bash
# COLOR
COff='\033[0m'       # Text Reset
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
bw='\033[1;37m'
#choose
w=w
help=help
list=list
clear=clear
banner=banner
nol=0
satu=1
dua=2
tiga=3
empat=4
lima=5
help(){
echo
echo -e "help         help"
echo -e "list         list"
echo -e "clear        clear screen"
echo -e "banner       banner"
echo
}
date=`date`
list(){
echo
echo -e -ne "\t\t\t\t\t${BBlue}💀:: ${BRed}0.Exit\n"
echo -e -ne "\t\t\t\t\t${BBlue}💀:: ${bw}1.ffuf\n"
echo -e -ne "\t\t\t\t\t${BBlue}💀:: ${bw}2.wfuzz\n"
echo -e -ne "\t\t\t\t\t${BBlue}💀:: ${bw}3.CMS\n"
echo -e -ne "\t\t\t\t\t${BBlue}💀:: ${bw}4.ENCYDECY\n"
}
banner(){
echo -e "${BRed}"
echo -e -ne "\t\t\t\t\t\t\tAutomations" | figlet -f slant
echo -e -ne "${BRed}\t\t<================${BWhite}$date${BRed}================>\n"
}
clear
banner
list
while true
do
PS2=${BBlue}'┌──('${BRed}'Choose💀Options'${BBlue}')-['']\n└─'${BRed}'# '${BWhite}
echo -ne "$PS2"
read  -p "" pilih
if [ $nol = $pilih ]; then
    exit
elif [ $clear == $pilih  ]; then
    clear
elif [ $list == $pilih ]; then
    banner
    list
elif [ $help == $pilih ]; then
    help
elif [ $banner == $pilih ]; then
    banner
elif [ $satu == $pilih ] ; then
    ffufauto
elif [ $dua == $pilih ] ; then
    wfuzzauto
elif [ $tiga == $pilih ] ; then
    cms
elif [ $empat == $pilih ] ; then
    encydecy
else
  echo -e "${BRed}Pilihan Salah${BWhite}"

fi
done
