#!/bin/bash
# COLOR
COff='\033[0m'       # Text Reset
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
bw='\033[1;37m'
echo -e "${BRed}"
echo -e "   )  ("
echo -e " ( /(  )\ )"
echo -e " )\())(()/(          (     )  ("
echo -e "((_)\  /(_))   )    ))\ ( /(  )("
echo -e '  ((_)(_))  /(/(   /((_))(_))(()\'
echo -e '           ((_)_\ (_)) ((_)_  ((_)'

echo -e "${BRed}"
echo -e "   )  (                      )  ("
echo -e " ( /(  )\ )		  ( /(  )\ )"
echo -e " )\())(()/(		  )\())(()/("
echo -e "((_)\  /(_))		 ((_)\  /(_))"
echo -e '  ((_)(_))		   ((_)(_))'
echo -e


echo -e "           (     )  ("
echo -e "    )    ))\ ( /(  )("
echo -e ' /(/(   /((_))(_))(()\'
echo -e '((_)_\ (_)) ((_)_  ((_)'


