#!/bin/bash
# COLOR
COff='\033[0m'       # Text Reset
# Bold
BBlack='\033[1;30m'       # Black
BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White
bw='\033[1;37m'
#choose
h=h
l=l
clear=clear
nol=0
satu=1
dua=2
tiga=3
empat=4
lima=5

echo -e "${BWhite}├─${BRed}[0].Exit"
echo -e "${BWhite}├─${BGreen}[${bw}1${BGreen}].SQL"
echo -e "${BWhite}├─${BGreen}[${bw}2${BGreen}].XSSHUNTER"
#echo -e "${BWhite}├─${BGreen}[${bw}3${BGreen}]."
#echo -e "${BWhite}├─${BGreen}[${bw}4${BGreen}]."
#echo -e "${BWhite}├─${BGreen}[${bw}5${BGreen}]."
#echo -e "${BWhite}├─${BGreen}[${bw}6${BGreen}]."
#echo -e "${BWhite}├─${BGreen}[${bw}7${BGreen}]."
#echo -e "${BWhite}├─${BGreen}[${bw}8${BGreen}]."
#echo -e "${BWhite}├─${BGreen}[${bw}9${BGreen}]."
while true
do
read -p "Masukkan Pilihan : " pilih
if [ $nol == $pilih  ]; then
	exit
elif [ $clear == $pilih  ]; then
	clear
elif [ $satu == $pilih  ]; then
	cd /home/kali/payloads
	./sqli
elif [ $dua == $pilih  ]; then
	cd /home/kali/payloads
	./xsshunter
else
	echo -e "${BRed}Tidak ada${BGreen}"
fi
done
